// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCRuzwL-wXgOKGIOkszrCLzC8i5WQ_yjWY',
    appId: '1:601728385548:web:71c13a16bbe2dab810e429',
    messagingSenderId: '601728385548',
    projectId: 'ecommerce-practice-be506',
    authDomain: 'ecommerce-practice-be506.firebaseapp.com',
    storageBucket: 'ecommerce-practice-be506.firebasestorage.app',
    measurementId: 'G-8P40WQSH3N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-KcpDRfBwFilqKbOrCML3jXAK8mB9daQ',
    appId: '1:601728385548:android:8d6240687178c97110e429',
    messagingSenderId: '601728385548',
    projectId: 'ecommerce-practice-be506',
    storageBucket: 'ecommerce-practice-be506.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVgKp-_ifmD4IV-1P_8lUSuls0KMZbm3s',
    appId: '1:601728385548:ios:54c650d88925d85310e429',
    messagingSenderId: '601728385548',
    projectId: 'ecommerce-practice-be506',
    storageBucket: 'ecommerce-practice-be506.firebasestorage.app',
    iosClientId: '601728385548-hhslvfbr1lf5innldoq9i449tdltp7el.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecommercePractice',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCVgKp-_ifmD4IV-1P_8lUSuls0KMZbm3s',
    appId: '1:601728385548:ios:54c650d88925d85310e429',
    messagingSenderId: '601728385548',
    projectId: 'ecommerce-practice-be506',
    storageBucket: 'ecommerce-practice-be506.firebasestorage.app',
    iosClientId: '601728385548-hhslvfbr1lf5innldoq9i449tdltp7el.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecommercePractice',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCRuzwL-wXgOKGIOkszrCLzC8i5WQ_yjWY',
    appId: '1:601728385548:web:fd33f3ea00da284910e429',
    messagingSenderId: '601728385548',
    projectId: 'ecommerce-practice-be506',
    authDomain: 'ecommerce-practice-be506.firebaseapp.com',
    storageBucket: 'ecommerce-practice-be506.firebasestorage.app',
    measurementId: 'G-2HB9WBZVF7',
  );
}
